apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-challenge-deployment
spec:
  selector:
    matchLabels:
      app: docker-challenge
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-challenge
    spec:
      containers:
      - name: docker-challenge
        image: marziehvahid/docker-challenge:latest
        ports:
        - containerPort: 80
        - containerPort: 8090
